baseURL = "https://uapi-group.org"
languageCode = "en-us"
title = "The Linux Userspace API Group"
theme = "hugo-book"

[[menu.after]]
  name = "Specifications"
  url = "https://uapi-group.org/specifications"
  weight = 10
[[menu.after]]
  name = "General Documentation"
  url = "https://uapi-group.org/docs"
  weight = 11
[[menu.after]]
  name = "Kernel Feature Ideas"
  url = "https://uapi-group.org/kernel-features"
  weight = 12

[[menu.after]]
  name = "Collaborate on Github"
  url = "https://github.com/uapi-group"
  weight = 21

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  BookSearch = false
  BookRepo = 'https://github.com/uapi-group/uapi-group.github.io'
  BookEditLink = '{{ .Site.Params.BookRepo }}/edit/main/{{ .Path }}'
